import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import AuthSession from './session';
import Nav from '@/components/nav';

const inter = Noto_Sans_KR({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'MusicBoard',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <AuthSession>
            <Nav />
            {children}
          </AuthSession>
        </body>
      </html>
    </>
  );
}
